src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
#[Broadcast]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $Nom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }
}

src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
#[Broadcast]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(name:"idCategories", nullable: false)]
    private ?Categories $idCategories = null;

    #[ORM\Column(name:"nomproduits", length: 255)]
    private ?string $nomproduits = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column(name:"dateajout", type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateajout = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCategories(): ?Categories
    {
        return $this->idCategories;
    }

    public function setIdCategories(?Categories $idCategories): static
    {
        $this->idCategories = $idCategories;

        return $this;
    }

    public function getNomProduits(): ?string
    {
        return $this->nomproduits;
    }

    public function setNomProduits(string $nomproduits): static
    {
        $this->nomproduits = $nomproduits;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->dateajout;
    }

    public function setDateAjout(\DateTimeInterface $dateajout): static
    {
        $this->dateajout = $dateajout;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
{% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">StockTrack</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            {% if app.user %}
                                <li class="nav-item d-inline-block">
                                    <a class="nav-link" href="{{ path('app_home_page') }}">Accueil</a>
                                </li>
                                <li class="nav-item d-inline-block">
                                    <a class="nav-link" href="{{ path('app_produits') }}">Ajouter un Produit</a>
                                </li>
                                <li class="nav-item d-inline-block">
                                    <a class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>
                                </li>
                            {% else %}
                                <li class="nav-item d-inline-block">
                                    <a class="nav-link" href="{{ path('app_login') }}">Connexion</a>
                                </li>
                                <li class="nav-item d-inline-block">
                                    <a class="nav-link" href="{{ path('app_register') }}">Inscription</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
    </body>
        {% block body %}
        <h1>Hello new !</h1>
        <div class="container">
        {% for produit in produits %}
        <div class="card">
            <h3>Nom : {{produit.nomproduits}}</h3>
            <p>Description : {{produit.description}}</p>
            <p>Nom de la categories : {{produit.idCategories.nom}}</p>
            <p>Date de l'ajout : {{produit.dateajout|date('d-m-Y')}}</p>
            <p>Prix : {{produit.prix}}</p>
            <p>Quantiter  : {{produit.quantity}}</p>
        </div>
        {% endfor %}
        {# <a href="{{ path('PRODUITS') }}">Produits</a> #}
        <div>
        {% endblock %}
        
    
</html>